name: Deploy Hugo to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: '0.145.0'

      - name: Build
        run: hugo --minify

      - name: Check built site
        run: ls -l docs/ && test -f docs/index.html && echo "index.html exists" || echo "index.html missing"
      - name: Commit and push to main
        run: |
          git config user.name "GitHub Actions Bot"
          git config user.email "actions@github.com"
          git add docs/ content/recipes/
          git commit -m "Update site " || echo "No changes to commit"
          git stash
          git pull origin main
          git push origin main